### ISSUE TITLE
Research CSS Frameworks

### ISSUE THREAD

**Issue by Jameson42** [KenoshaLUG/LUGServicesWebClient#4]
Research and compare the following CSS Frameworks:

* Bootstrap
* Foundation
* Skeleton
* Pure

Key considerations:

* Ease of use
* Interaction with Angular
* Available elements
* Freely available

**Comment by Jameson42** [comment]
Bootstrap has a lot of JS integration that works poorly with Angular. Ruling it out for now.

Foundation is EXTENSIVE... lots of stuff built in. Pretty good looking.

Skeleton is very bare-bones, but looks good.

Pure looks pretty good as well.

I'm leaning towards Foundation or Skeleton.

**Comment by MKELEGOGuy** [comment]
Have you considered Angular Material? https://material.angular.io/

I do agree Foundation is very impressive. I'm just wondering about how easy it will be to pick-up.

Skeleton is as you say bare bones. I'd prefer going with Angular Material, if we went with something so simple.

**Comment by Jameson42** [comment]
Angular Material looks really nice. I'm a fan of Material Design. 

There looks to be a pretty heavy focus on using Node.js and NPM for that... but someone's built a NuGet package for it that we should be able to use if we want to stick to ASP.NET MVC.  I'm not opposed to trying Node for the frontend though... any thoughts?

**Comment by Jameson42** [comment]
Did some testing with Angular Material, I'm not impressed with it. It seems very focused on long vertical pages (example here: https://material2-app.firebaseapp.com/). Nothing built-in for layouts, tables, etc.  

I'm trying out Angular 4 with Boostrap 4 using https://ng-bootstrap.github.io on my Derby frontend, we'll see how that goes after I've had a few days working with it. I like the layout flexibility of Bootstrap, and the components look nice as well.

**Comment by Jameson42** [comment]
Recommending Bootstrap 4 with ng-bootstrap for CSS framework.
